
module std_msgs { 
    module msg { 
 
        @nested 
        struct Time { 
            long sec; 
            unsigned long nanosec; 
        }; 

        @nested
        struct Header { 
            std_msgs::msg::Time stamp; 
            string frame_id; 
        }; 

    }; 
};
  
module geometry_msgs { 
    module msg { 
 
        struct Point { 
            double x; 
            double y; 
            double z; 
        }; 

        struct Quaternion { 
            double x; 
            double y; 
            double z; 
            double w; 
        }; 

        struct Vector3 { 
            double x; 
            double y; 
            double z; 
        }; 

        struct Pose { 
            geometry_msgs::msg::Point position; 
            geometry_msgs::msg::Quaternion orientation; 
        };

        struct Twist { 
            geometry_msgs::msg::Vector3 linear; 
            geometry_msgs::msg::Vector3 angular; 
        }; 

        typedef double geometry_msgs__PoseWithCovariance__double_array_36[36]; 
        
        struct PoseWithCovariance { 
            geometry_msgs::msg::Pose pose; 
            geometry_msgs__PoseWithCovariance__double_array_36 covariance; 
        }; 

        typedef double geometry_msgs__TwistWithCovariance__double_array_36[36]; 
 
        struct TwistWithCovariance { 
            geometry_msgs::msg::Twist twist; 
            geometry_msgs__TwistWithCovariance__double_array_36 covariance; 
        }; 

    }; 
};  

module nav_msgs { 
    module msg { 
 
        struct Odometry { 
            std_msgs::msg::Header header; 
            string child_frame_id; 
            geometry_msgs::msg::PoseWithCovariance pose; 
            geometry_msgs::msg::TwistWithCovariance twist; 
        }; 
    
    }; 
};  