/*
* (c) Copyright, Real-Time Innovations, 2020.  All rights reserved.
* RTI grants Licensee a license to use, modify, compile, and create derivative
* works of the software solely for use with RTI Connext DDS. Licensee may
* redistribute copies of the software provided that all such copies are subject
* to this license. The software is provided "as is", with no warranty of any
* type, including any warranty for fitness for any purpose. RTI is under no
* obligation to maintain or support the software. RTI shall not be liable for
* any incidental or consequential damages arising out of the use or inability
* to use the software.
*/

module control {

    const string THROTTLE_CMD_TOPIC_NAME = "Throttle Command Topic";
    const string BRAKE_CMD_TOPIC_NAME = "Brake Command Topic";
    const string ENGAGEMENT_TYPE_NAME = "control::Engagement";

    enum Device_Type {
        THROTTLE,
        BRAKE
    };

    struct Engagement {
        @key long device_id;
        Device_Type device_type;
        long percentage;
    };
};