module control {

    const string THROTTLE_CMD_TOPIC_NAME = "Throttle Command Topic";
    const string BRAKE_CMD_TOPIC_NAME = "Brake Command Topic";
    const string ENGAGEMENT_TYPE_NAME = "control::Engagement";

    enum Device_Type {
        THROTTLE,
        BRAKE
    };

    struct Engagement {
        @key long device_id;
        Device_Type device_type;
        long percentage;
    };
};